version: '3.1'
services:
  db:
    image:
      postgres
    environment:
      POSTGRES_USER: keker
      POSTGRES_PASSWORD: kek
      POSTGRES_DB: betdb
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - "dbdata:/var/lib/postgresql/data"
    command: ["postgres", "-c", "log_statement=all"]
  api_parse:
    build:
      ./apiParser
    ports:
      - 5555:5555
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./apiParser/loggg.log:/app/loggg.log
volumes:
  dbdata:
