version: '3.1'
services:
  db:
    build:
      ./db
    ports:
    - 5432:5432
  apiparse:
    build:
      ./apiParser
    ports:
      - 5555:5555
    links:
      - db
    depends_on:
      - db
  backend:
    build:
      ./backend
    ports:
      - 666:666
    links:
      - db
      - apiparse
    depends_on:
      - db
      - apiparse

