version: '3.1'
services:
  db:
    image:
      postgres
    environment:
      POSTGRES_USER: keker
      POSTGRES_PASSWORD: everybodykissmybody
      POSTGRES_DB: betdb
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api_parse:
    build:
      ./apiParser
    ports:
      - 5555:5555
    links:
      - db
    depends_on:
      - db
