version: '3.0'
services:
  db:
    image:
      postgres
    environment:
      POSTGRES_USER: keker
      POSTGRES_PASSWORD: everybodykissmybody
      POSTGRES_DB: BetDB
    ports:
      - 5432:5432
  api_parse:
    image:
      ./apiParser
    ports:
      - 5555:5555
    links:
      - db
